server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /product/ {
        root /usr/share/nginx/html;
        try_files $uri /pages/product_info.html;
    }

    # Proxy API requests to the backend service
    # So that the frontend can communicate with the backend without CORS issues

    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy product image requests to MinIO
    # Only /image/product/ is forwarded; assets/ stays on Nginx
    location /image/product/ {
        proxy_pass http://minio:9000/product-image/;
        proxy_set_header Host minio:9000;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
