services:
  backend_service:
    image: backend:latest
    build:
      context: .
      dockerfile: ./infra/service/Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - backend_network

  mongodb:
    image: mongodb:latest
    build:
      context: ./infra/mongodb
      dockerfile: Dockerfile
    container_name: mongodb
    networks:
      - backend_network

  minio:
    build:
      context: ./infra/minio
      dockerfile: Dockerfile
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./infra/minio/product:/home/image   # host image folder → container
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge